### ISSUE TITLE
[cpanel_uapi] deploying staging cert fail with success

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#1042]
```
acme.sh --deploy --domain fr.vamosportls.imperialus.house --deploy-hook cpanel_uapi
[2017-09-24 07:35:39 -0400] warn [cpanel] Cpanel::Wrap::send_cpwrapd_request The adminbin “ssl” in the “Cpanel” namespace call to function “ADD” ended prematurely: The subprocess reported error number 5 when it ended.: namespace=[Cpanel] module=[ssl] function=[ADD]: raw_response=[{"error":1,"version":"2.4","action":"fetch","timeout":0,"exit_code":1280,"data":{"statusmsg":"Certificate verification failed!The system did not find the Certificate Authority Bundle that matches this certificate.Contact “Fake LE Intermediate X1” to obtain the Certificate Authority Bundle.","status":0,"html":"Certificate verification failed!The system did not find the Certificate Authority Bundle that matches this certificate.Contact “Fake LE Intermediate X1” to obtain the Certificate Authority Bundle.","message":"Certificate verification failed!The system did not find the Certificate Authority Bundle that matches this certificate.Contact “Fake LE Intermediate X1” to obtain the Certificate Authority Bundle.","action":"install"},"status":1,"statusmsg":"The adminbin “ssl” in the “Cpanel” namespace call to function “ADD” ended prematurely: The subprocess reported error number 5 when it ended.","mode":"full"}] at /usr/local/cpanel/Cpanel/Wrap.pm line 124, <$socket> line 1.
	Cpanel::Wrap::send_cpwrapd_request("module", "ssl", "function", "ADD", "env", HASH(0x5f90bf0), "no_cperror", 1, "data", ...) called at /usr/local/cpanel/Cpanel/Wrap.pm line 64
	Cpanel::Wrap::send_cpwrapd_request_no_cperror("namespace", "Cpanel", "module", "ssl", "function", "ADD", "data", HASH(0x2b65400), "action", ...) called at /usr/local/cpanel/Cpanel/AdminBin.pm line 251
	Cpanel::AdminBin::_adminfetch("module", "ssl", "function", "ADD", "format", "storable", "cache_check_files", "", "cache", ...) called at /usr/local/cpanel/Cpanel/AdminBin.pm line 177
	Cpanel::AdminBin::fetch_adminbin_nocache_with_status("ssl", undef, "ADD", "storable", HASH(0x2b65400)) called at /usr/local/cpanel/Cpanel/API/SSL.pm line 1713
	Cpanel::API::SSL::_install("fr.vamosportls.imperialus.house", "fr_vamosportls_imperialus_house_cb0e6_06ad7_1514025240_e785a6"..., "cb0e6_06ad7_e0dba6d35cbdfbafce5c7159dcc59ede", undef, Cpanel::Result=HASH(0x5ad1328)) called at /usr/local/cpanel/Cpanel/API/SSL.pm line 1334
	Cpanel::API::SSL::install_ssl(Cpanel::Args=HASH(0x5ad1568), Cpanel::Result=HASH(0x5ad1328)) called at /usr/local/cpanel/Cpanel/API.pm line 287
	Cpanel::API::__ANON__() called at /usr/local/cpanel/Cpanel/API.pm line 359
	eval {...} called at /usr/local/cpanel/Cpanel/API.pm line 359
	Cpanel::API::_eval_guard(Cpanel::Result=HASH(0x5ad1328), CODE(0x5ad1748)) called at /usr/local/cpanel/Cpanel/API.pm line 287
	Cpanel::API::_run_module_function(Cpanel::Args=HASH(0x5ad1568), Cpanel::Result=HASH(0x5ad1328), "SSL", "install_ssl") called at /usr/local/cpanel/Cpanel/API.pm line 142
	Cpanel::API::execute("SSL", "install_ssl", HASH(0x5ad51b8)) called at cpanel.pl line 1480
	cpanel::cpanel::docpanelaction(HASH(0x5ad1160)) called at cpanel.pl line 4996
	cpanel::cpanel::run_fast_json_mode() called at cpanel.pl line 840
	cpanel::cpanel::script("cpanel::cpanel", "--json-fast-connect", "--stdin") called at cpanel.pl line 306
[2017-09-24 07:35:39 -0400] warn [cpanel] Cpanel::Wrap::send_cpwrapd_request error: namespace=[Cpanel] module=[ssl] function=[ADD]: statusmsg=[The adminbin “ssl” in the “Cpanel” namespace call to function “ADD” ended prematurely: The subprocess reported error number 5 when it ended.] at /usr/local/cpanel/Cpanel/Wrap.pm line 133, <$socket> line 1.
	Cpanel::Wrap::send_cpwrapd_request("module", "ssl", "function", "ADD", "env", HASH(0x5f90bf0), "no_cperror", 1, "data", ...) called at /usr/local/cpanel/Cpanel/Wrap.pm line 64
	Cpanel::Wrap::send_cpwrapd_request_no_cperror("namespace", "Cpanel", "module", "ssl", "function", "ADD", "data", HASH(0x2b65400), "action", ...) called at /usr/local/cpanel/Cpanel/AdminBin.pm line 251
	Cpanel::AdminBin::_adminfetch("module", "ssl", "function", "ADD", "format", "storable", "cache_check_files", "", "cache", ...) called at /usr/local/cpanel/Cpanel/AdminBin.pm line 177
	Cpanel::AdminBin::fetch_adminbin_nocache_with_status("ssl", undef, "ADD", "storable", HASH(0x2b65400)) called at /usr/local/cpanel/Cpanel/API/SSL.pm line 1713
	Cpanel::API::SSL::_install("fr.vamosportls.imperialus.house", "fr_vamosportls_imperialus_house_cb0e6_06ad7_1514025240_e785a6"..., "cb0e6_06ad7_e0dba6d35cbdfbafce5c7159dcc59ede", undef, Cpanel::Result=HASH(0x5ad1328)) called at /usr/local/cpanel/Cpanel/API/SSL.pm line 1334
	Cpanel::API::SSL::install_ssl(Cpanel::Args=HASH(0x5ad1568), Cpanel::Result=HASH(0x5ad1328)) called at /usr/local/cpanel/Cpanel/API.pm line 287
	Cpanel::API::__ANON__() called at /usr/local/cpanel/Cpanel/API.pm line 359
	eval {...} called at /usr/local/cpanel/Cpanel/API.pm line 359
	Cpanel::API::_eval_guard(Cpanel::Result=HASH(0x5ad1328), CODE(0x5ad1748)) called at /usr/local/cpanel/Cpanel/API.pm line 287
	Cpanel::API::_run_module_function(Cpanel::Args=HASH(0x5ad1568), Cpanel::Result=HASH(0x5ad1328), "SSL", "install_ssl") called at /usr/local/cpanel/Cpanel/API.pm line 142
	Cpanel::API::execute("SSL", "install_ssl", HASH(0x5ad51b8)) called at cpanel.pl line 1480
	cpanel::cpanel::docpanelaction(HASH(0x5ad1160)) called at cpanel.pl line 4996
	cpanel::cpanel::run_fast_json_mode() called at cpanel.pl line 840
	cpanel::cpanel::script("cpanel::cpanel", "--json-fast-connect", "--stdin") called at cpanel.pl line 306
[Sun Sep 24 07:35:39 EDT 2017] Certificate successfully deployed
[Sun Sep 24 07:35:39 EDT 2017] Success
```

**Comment by FernandoMiguel** [comment]
Cc @2globalnomads 

issue a --staging cert
then deploy with cpanel_uapi hook.
although it fails to upload to cpanel db, it still states success.

**Comment by 2globalnomads** [comment]
Thanks! Does this work for you any better: https://github.com/2globalnomads/acme.sh/blob/patch-5/deploy/cpanel_uapi.sh ?

**Comment by FernandoMiguel** [comment]
@2globalnomads 
much better message yes

```
[Tue Sep 26 06:54:16 EDT 2017] Error in deploying certificate:
[Tue Sep 26 06:54:16 EDT 2017] ---
apiversion: 3
func: install_ssl
module: SSL
result:
  data:
    cert_id: fr_vamosportls_imperialus_house_cb0e6_06ad7_1514195640_828e6782c683b5e0a963f51fd1d17e59
    key_id: cb0e6_06ad7_e0dba6d35cbdfbafce5c7159dcc59ede
  errors:
    - The certificate could not be installed on the domain “fr.vamosportls.imperialus.house”.
    - Certificate verification failed!The system did not find the Certificate Authority Bundle that matches this certificate.Contact “Fake LE Intermediate X1” to obtain the Certificate Authority Bundle.
  messages: ~
  metadata: {}

  status: 0
[Tue Sep 26 06:54:16 EDT 2017] Error deploy for domain:fr.vamosportls.imperialus.house
[Tue Sep 26 06:54:16 EDT 2017] Deploy error.
```
