### ISSUE TITLE
Docker installation fails /  Unclear instructions

### ISSUE THREAD

**Issue by simonszu** [Neilpang/acme.sh#1443]
Installation via docker fails. After starting a container in daemon mode, the next step to execute is to execute `--install`, i suppose, since the docker environment is quite similar to plain installation. If not, the instructions for docker are a bit unclear. 

Steps to reproduce
------------------
Start acme.sh docker container with this docker-compose settings (a bit differently from plain docker compose, since i use ansible, but the general semantics should be the same)
```
- name: Start docker service
  docker_service:
    pull: yes
    project_name: acmesh
    definition:
      version: '2'
      services:
        app:
          restart: unless-stopped
          image: neilpang/acme.sh
          volumes:
          - "{{ docker_datadir }}/acme.sh/out:/acme.sh"
          command: daemon
          networks:
          - default
      networks:
        default:
          external:
            name: backend
  become: yes
```
Result: Container is running and is called `acmesh_app_1`. Next step: Trying to register an account via acme protocol:
`docker exec acmesh_app_1 --install --accountemail "mail@simonszu.de"`

Result:
```
[Sat Mar 24 08:21:40 UTC 2018] Installing to /root/.acme.sh
cp: omitting directory 'acme.sh'
[Sat Mar 24 08:21:40 UTC 2018] Install failed, can not copy acme.sh
```
The dockerfile already configures the acme.sh inside the container to have it's home in `/acme.sh`, so i am wondering why it tries to write to `/root`. This will change the content of the container outside of any volumes, so it's not very desireable. 


Debug log
-----------------
```
$ docker exec acmesh_app_1 --debug 2                                                                                                                                                                                                                       1 [09:21:40]
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"--debug\": executable file not found in $PATH": unknown
```
