### ISSUE TITLE
Error deploying certificate with cPanel Uapi command

### ISSUE THREAD

**Issue by gl-Hub** [Neilpang/acme.sh#1713]
Hello,

I've successfully used the following acme.sh commands until --deploy, when an error is displayed:

```
acme.sh --issue -d domain.com -d www.domain.com -w /home/user/public_html --keylength ec-384 --staging --debug --log

acme.sh --issue -d domain.com -d www.domain.com -w /home/user/public_html --keylength ec-384 --debug --log --force
```

Addedd "export DEPLOY_CPANEL_USER=cPanel username" to cpanel_uapi.sh

`acme.sh --deploy -d domain.com --deploy-hook cpanel_uapi --ecc`

```
[Wed Jul  4 03:42:52 MST 2018] Error in deploying certificate:
[Wed Jul  4 03:42:52 MST 2018] ---
apiversion: 3
func: install_ssl
module: SSL
result:
  data: ~
  errors:
    - "The system could not parse the certificate because of an error: The ASN.1 data is corrupt. Its header indicates a length of 89 bytes, but its content is 97 bytes long."
  messages: ~
  metadata: {}

  status: 0
[Wed Jul  4 03:42:52 MST 2018] Error deploy for domain:domain.com
[Wed Jul  4 03:42:52 MST 2018] Deploy error.
```

Any suggestion is welcomed.
