### ISSUE TITLE
Docker: how to reload nginx container after certificate renewal

### ISSUE THREAD

**Issue by chinkung** [Neilpang/acme.sh#816]
I have installed docker with docker-compose and here is my docker-compose.yml

```  
nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
  letsencrypt:
    image: neilpang/acme.sh:latest
    container_name: acme.sh
    restart: always
    command: daemon
    volumes_from:
      - nginx
    depends_on:
      - nginx
```

I can issue my SSL certificate using these command (I have already setup server configuration as describe in [Stateless mode](https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode)) without any problem.

```
$ docker exec acme.sh --issue -d <DOMAIN> --stateless
$ docker exec acme.sh --install-cert -d <DOMAIN> \
--keypath       /etc/nginx/certs/shared.key  \
--fullchainpath /etc/nginx/certs/shared.pem 
```

The question is how can I pass **--reloadcmd  <xxxxxx>** to **--install-cert** to automatically reload nginx docker after certificate renewal ?
